[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

# for linux 
# decorations = "none"

# for macos 
# decorations = "Buttonless"

opacity = 0.95
blur = true

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 12.0

